language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
  - sudo apt-get update
  - sudo apt-get install -qq python-simpleparse antiword poppler-utils tesseract-ocr tesseract-ocr-swe tesseract-ocr-osd tidy xsltproc
  - pip install -U setuptools
services:
  - elasticsearch
install:
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '2' ]]; then pip install -r requirements.py2.txt; fi
  - if [[ ${TRAVIS_PYTHON_VERSION%%.*} == '3' ]]; then LANG=en_US.UTF-8 pip install -r requirements.py3.txt; fi
  - pip install coveralls
  - python -c 'from lxml import etree; print(etree.LIBXML_VERSION, etree.LIBXML_COMPILED_VERSION, etree.LIBXSLT_VERSION, etree.LIBXSLT_COMPILED_VERSION)'
script:
   - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then PYTHONWARNINGS=i coverage run --include "ferenda/*py" --omit "ferenda/thirdparty/*" -m unittest2 discover -v test; fi
   - if [[ $TRAVIS_PYTHON_VERSION != '2.6' ]]; then PYTHONWARNINGS=i coverage run --include "ferenda/*py" --omit "ferenda/thirdparty/*" -m unittest discover -v test; fi
after_success:
  - coveralls
